title: Philippe Forest # your name (or website title) here
logo: "/images/test.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Data visualization, analytics and analysis 
  <br>
  The projects presented on this page range from Deep learning to Data visualization, using many different methods in domains as diverse as text recognition, intellectual rights protection, video captioning or music features analysis
  <br><br>
  <a href="https://www.linkedin.com/in/philippe-forest/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
